version: '3'
services:
  gpt-researcher:
    image: assafelovic/gpt-researcher
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      OPENAI_API_TYPE: ${OPENAI_API_TYPE}
      BING_API_KEY: ${BING_API_KEY}
      SEARCH_DOMAIN: ${SEARCH_DOMAIN}
    ports:
      - 8000:8000